### PR TITLE
generate_solr_document should yield the document

### PR DESCRIPTION
**Pull request by jcoyne**
This follows the pattern used by ActiveFedora.

### CODE REVIEW

**Comment by atz** [comment]
Talking to @jcoyne, this PR is a candidate to be reverted, since downstream consumers/extenders cannot use both `super.tap { |solr_doc| ... }` and `super { |solr_doc| ... }` interchangeably.  Currently Hyrax uses and generates `super.tap` code, so our preference should probably be there.

Looking at https://github.com/projecthydra-labs/hyrax/blob/3a6c072f6dfad1bc8a7ec3c9d6c81f441e1ce6e9/app/indexers/hyrax/collection_indexer.rb#L10-L21

The intent of the yield is to give the block the doc (hash) AFTER the method has applied its changes. 
 But this accesses an unpopulated field:
```ruby
Hyrax::CollectionIndexer.new.generate_solr_document { |doc| doc['thumbnail_path_ss'] }
```
Because the block isn't yielded to at the end, rather **inside** the `super` call, before Hyrax fields have been added.  The inheritance context of the methods makes this approach questionable.  

@mjgiarlo: any comment?

**Comment by atz** [comment]
See: https://github.com/projecthydra/active_fedora/issues/1250

**Comment by atz** [comment]
@jcoyne Confirm reversion?

**Comment by jcoyne** [comment]
@atz do we have a test we can add that shows this problem in action?  I'd like to revert this revert somewhere down the road and I'd like a test to point to and say: "See, not a problem anymore"

**Comment by atz** [comment]
@jcoyne Yes, I have a test in my Hyrax branch, but I can also add a test here if you want.  AFAIK, this is literally not fixable without some magic that then has to be reproduced in all descendants also, so I cannot project a time where we could ever seamlessly reapply these changes.  It is not a pattern that can be cleanly inherited.  

This problem goes all the way down to ActiveFedora.

**Comment by jcoyne** [comment]
I would appreciate it if you'd put that spec in.

**Comment by atz** [comment]
https://github.com/samvera/hydra-pcdm/pull/241

**Pull request merged**
